language: java

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
    - develop

install: 
  - PATH=$TRAVIS_BUILD_DIR:$PATH
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - curl -fL https://getcli.jfrog.io | sh
  - chmod +x jfrog
  - jfrog rt config "cishell-artifactory" --url "https://cishell.jfrog.io/cishell/" --user $CI_DEPLOY_USERNAME --apikey $CI_DEPLOY_PASSWORD --interactive=false

script: 
  - mvn deploy &&
    cd $TRAVIS_BUILD_DIR/sci2/deployment/edu.iu.sci2.p2/target/repository &&
    jfrog rt delete "sci2/updates/*" --quiet &&
    jfrog rt upload "./*" "sci2/updates/" --flat=false &&
    cd $TRAVIS_BUILD_DIR/sci2/deployment/org.cishell.sci2.releng/target/products-final &&
    jfrog rt delete "sci2/latest/*" --quiet &&
    jfrog rt upload "./*" "sci2/latest/" --flat=false
